/**
 * Design handoff — KeepItCool landing (Figma).
 *
 * Fonte di verità per stato redesign e decisioni approvate.
 * Aggiornare a ogni step approvato dall'utente.
 */

export const DESIGN_HANDOFF = {
  figmaUrl: "https://www.figma.com/design/h8h30JRo9ffjr9tXxvcI5j/Sito?node-id=89-3655",
  contentBrief: "app/content/project-brief.js",
  status: "phase-2c-complete",
  currentStep: 7,
  currentStepName: "Landing completa (Phase 2c)",
  approved: [
    "Step 0 — design tokens (/styleguide)",
    "Font: Chillax Bold (local) + Outfit (Google variable)",
    "Ink: ink #2c2c2c (main), ink-muted #434343 (secondary), ink-warm #503b14 (CTA on yellow)",
    "CTA: radial gradient btn-cta — not flat #fad724",
    "highlight-yellow: flat mark under text (bottom 0.22em)",
    "SDG colors scoped to 4 Learning Goals cards only",
    "Game cards: game-card-talk/plan/play gradients scoped to Game section",
    "Tag student gradient ends #708721 (was too dark at #435310)",
    "Tag team member names reuse tag-psychologist style",
    "nav-pill / nav-pill-sticky: classi CSS normali in globals.css (come btn-cta), cream 50% + backdrop-blur(12px)",
    "Step 1 — Navbar: logo Figma (/images/logo.svg), mix-blend-multiply, wrapper isolate",
    "Step 1 — layout desktop centrato: logo | nav-pill | Get in touch, gap 100px",
    "Step 1 — nav-pill-sticky sul wrapper pill (pattern /styleguide), header sticky top-4 z-50",
    "Step 1 — link: How it works #how-it-works, Approach #approach, Partners #partners, About us #about (no hero)",
    "Step 1 — CTA Get in touch → #contact; desktop in header, mobile solo nel drawer",
    "Step 1 — mobile: hamburger in cerchio nav-pill; drawer cream-light/95 + blur",
    "Step 1 — scroll hash smooth, scroll-padding-top 5rem, no hide-on-scroll",
    "Step 2 — Hero: layout A centrato (Figma), titolo Chillax uppercase, sottotitolo Outfit",
    "Step 2 — CTA Join now (btn-cta) → #contact; no eyebrow, no seconda CTA",
    "Step 2 — 5 cartelline energy topics PNG (public/images/hero/), overlap/tilt desktop",
    "Step 2 — hover desktop: lift pronunciato (−22px, scale 1.08, straighten, ombra profonda)",
    "Step 2 — mobile (< md / 768px): carousel snap + auto-scroll 3.5s, .is-active al centro, pausa touch/wheel; da md fila overlapping (iPad incluso)",
    "Step 2 — sizing cartelle: row max 228px Figma, shrink quando 5 non entrano; carousel max 252px, inset 1rem (full-bleed)",
    "Step 2 — carousel: HeroFoldersCarousel client, spacers snap, ombre compatte mobile (no clip shadow)",
    "Step 2 — rimosso mock dashboard legacy (frost/mist/ice); copy HERO in sections.js",
    "Step 3 — GameSection dopo Hero, bg-cream; GameCard + GameCardStack + GameCardsRoot",
    "Step 3 — titolo text-section + highlight-yellow solo su «cooperative»; highlight draw-in dopo fade-up (.reveal, delay per stagger)",
    "Step 3 — reveal desktop: card TALK→PLAN→PLAY (0–2) poi titolo/body (3–4); mobile: titolo/body (0–1) poi card (2–4)",
    "Step 3 — desktop grid 530px|stack; card tilt −5°/+3°/−2°; gap 0.5rem statico (no overlap); testo centrato verticalmente vs stack",
    "Step 3 — gradient card ellipse 220% centro alto; end colori alleggeriti (#eb7589 / #3aaab0 / #e07848)",
    "Step 3 — 9 PNG public/images/game/{talk,plan,play}/asset-{1,2,3}; proporzioni native displayWidth",
    "Step 3 — asset posizioni finali: alto-destra / metà-sinistra / basso-sinistra; partono sotto card (centro), escono verso esterno",
    "Step 3 — scroll focus: card attiva solo se centro entro ~128px da centro viewport; scale + raddrizza + asset",
    "Step 3 — mobile: card quadrate aspect-square, tilt come desktop, stessa animazione asset/focus via GameCardsRoot",
    "Step 3 — asset timing: uscita 520ms stagger; rientro 760ms insieme (no stagger); card rientro 620ms",
    "Step 4 — anchor: Game → #how-it-works (blocco titolo+body); Energy → #approach; legacy HowItWorks senza id",
    "Step 4 — scroll #how-it-works: .scroll-anchor-how-it-works scroll-margin-top calc(5rem+6rem); grace period 600ms card focus su hash nav",
    "Step 4a — EnergySection id=approach dopo Game; titolo highlight su «future»; body centrato text-lead",
    "Step 4a — EnergyPhotoFan: 4 foto public/images/energy/ (user assets, crop quadrato); ventaglio desktop overlap + hover lift; mobile griglia 2×2 tilt leggero, no animazione",
    "Step 4b — LearningGoalsSection dopo Energy; titolo text-section text-ink-muted; padding-top ridotto vs Energy",
    "Step 4b — SdgCard ×4: bg-sdg-* scoped, border-10 white, icon SDG public/images/sdg/, copy Figma placeholder",
    "Step 4b — griglia 2 col mobile / 4 col md+; tilt desktop −7°/−3.5°/+3.5°/+7°; hover lift solo @media (hover: hover)",
    "Step 4b — SDG corner radius: --sdg-radius-inner = outer − padding (1.5rem − 1.25rem); .sdg-card__media; SdgCardMock allineato",
    "Step 5 — TestimonialsSection tra Learning Goals e Partners; no anchor navbar",
    "Step 5 — layout due blocchi: (A) titolo sinistra «Backed up from the target» + 3 card studenti destra; (B) 2 card esperti sinistra + titolo destra «and from experts»",
    "Step 5 — desktop studenti: card 1+2 impilate a sinistra, card 3 a destra; esperti affiancate in diagonale leggera davanti al titolo",
    "Step 5 — mobile: titolo → card stack distanziate (gap ~1.75rem); stesso ordine per entrambi i blocchi",
    "Step 5 — quote card bianca rounded-18px shadow-card; testo text-align left; pill sempre top-left su tutte le card",
    "Step 5 — pill 2 righe: line1 font-body xs (Student / nomi con iniziale maiuscola), line2 font-display text-ui uppercase",
    "Step 5 — tag studenti: tag-student (verde), tag-student-teal, tag-student-play; esperti: tag-psychologist + tag-expert-energy",
    "Step 5 — nuovi token scoped Testimonials: tag-student-teal / tag-student-play / tag-expert-energy in globals.css + /styleguide",
    "Step 5 — tilt per card da Figma; hover desktop straighten + lift; RevealOnScroll titolo delay 0, card 1–5 stagger",
    "Step 5 — copy placeholder Figma in TESTIMONIALS (sections.js); tono stakeholder da project-brief",
    "Step 6 — PartnersSection id=partners dopo Testimonials; titolo highlight-yellow su «energy sector»; no body",
    "Step 6 — 5 partner PNG RGBA: aet, SUPSI, ticino energia, WATT ABOUT, Dipartimento del territorio — public/images/partners/",
    "Step 6 — scatter desktop (3+2) + mobile scatter; cream-light box, float + tilt, overlap leggero sul titolo",
    "Step 6 — slot assoluti sul .reveal (non wrapper figlio); top-center via left calc(50% − metà box); PNG unoptimized",
    "Step 6 — ogni box link esterno target=_blank (href in PARTNERS.sections.js)",
    "Step 6 — PartnersFundedRow: «Project » + highlight «funded» + « by»; BRIDGE cream-light come partner; desktop row / mobile stack",
    "Step 6 — RevealOnScroll delay 0–7; partner-float / partner-float-mobile; reduced-motion disabilita float",
    "Cross-section — gap titolo→body adiacente: mt-6 (24px) su Hero, Game, Energy (era mt-10); Team body sotto foto — non applicato al titolo→ritratti",
    "Step 7 — TeamSection id=about dopo Partners; ordine: titolo → ritratti → body",
    "Step 7 — titolo «But who are we?» text-section text-ink-muted, no highlight",
    "Step 7 — body placeholder stakeholder centrato text-lead max-w 38rem; copy in TEAM sections.js",
    "Step 7 — 2 ritratti PNG user public/images/team/{matteo,marta}.png; tag-psychologist sui nomi",
    "Step 7 — tag + foto in .team-portrait__card: tilt e hover sulla card intera",
    "Step 7 — tilt −3°/+3° desktop, −2°/+2° mobile; overlap leggero desktop (left più bassa)",
    "Step 7 — hover desktop: overlay ink con portfolio → (link esterno) + mail → (mailto personale); straighten + lift −6px + scale 1.04",
    "Step 7 — portfolio: Matteo → marte.industries; Marta → instagram.com/marta.indd",
    "Step 7 — mail: matteodellagostino@gmail.com / martapiaatti@gmail.com",
    "Step 7 — mobile: portfolio → + mail → sotto foto; overlay solo hover/focus desktop",
    "Step 7 — RevealOnScroll delay 0 titolo, 1–2 ritratti, 3 body",
    "Step 8 — ContactSection (variante A Quiet close) dopo Team, id=contact; titolo «Want to learn more?» text-section text-ink-muted",
    "Step 8 — body stakeholder centrato text-lead max-w 38rem; copy in sections.js CONTACT",
    "Step 8 — CTA Get in touch btn-cta → mailto:info@keepitcool.ch; email in chiaro sotto come link mailto",
    "Step 8 — animazioni: solo RevealOnScroll fade-up delay 0–3; bg-cream",
    "Step 8 — legacy ContactCta rimosso da page.js; rimossi About/Features/HowItWorks (blocchi pre-redesign)",
    "Step 8 — preview B/C su /contact-preview/{b,c} (solo riferimento); A live come ContactSection",
    "Footer — bg-cream (come pagina), border-t-2 border-ink; layout 3 col desktop: brand | nav | email+copyright",
    "Footer — logo PNG logo-footer.png unoptimized (~6rem); tagline; nav hash come Navbar; mailto info@keepitcool.ch",
    "Footer — copyright © KEEP IT COOL; no Privacy/Terms (landing senza form — aggiungere solo se analytics/form)",
    "Footer — SITE metadata copy aggiornato a energy game (sections.js); altezza compatta py-6/7",
    "Home page order: Hero → Game → Energy → Learning Goals → Testimonials → Partners → Team → Contact → Footer",
    "Phase 2b Fix #1 — RevealOnScroll trigger anticipato: threshold 0.10, rootMargin bottom -2%",
    "Phase 2b Game assets desktop PLAY — approvato: play/asset-1 offsetY -145, offsetX 125",
    "Phase 2b Game assets mobile — approvato: z-index img sopra card; partenza off-screen per slot; arrivo invariato (offset/displayWidth desktop)",
    "Phase 2b Testimonials — desktop: più spazio studenti sx↔dx; esperti leggermente separati",
    "Phase 2b Testimonials — copy pill: Student + Elena Battipede (maiuscole); rimosso lowercase forzato su tag-line1",
    "Phase 2b Partners — hover desktop: overlay bianco rgba(255,255,255,0.82) + «website →» ink; lift invariato",
    "Phase 2c — Brief collega approvato: cooperative serious game, audience primaria educatori/scuole 15–18, tono chiaro/confident/non accademico, 5 messaggi chiave (balance, cooperation, play, no eco-anxiety, research-tested), EN primary, CTAs Get in touch / Bring to school / Partner",
    "Phase 2c — project-brief.js aggiornato con one-liner, short/long description, positioning, recognition BRIDGE + iF 2026, stakeholder rules",
    "Phase 2c — Favicon: app/icon.png 32×32 (K giallo, asset Frame_1208 collega); apple-icon.png allineato",
    "Phase 2c — SITE copy approvato: tagline «Energy literacy as a cooperative game»; description cooperative game (no serious) / young citizens / decisions, consequences, shared strategy; FOOTER.tagline allineato",
    "Phase 2c — OG/Twitter image: app/opengraph-image.png + twitter-image.png da logo-footer.png (1600×855); layout metadata da SITE",
    "Phase 2c — SEO: app/robots.js allow all + sitemap ref; layout alternates.canonical / → https://keepitcool.ch; lang en già ok",
    "Phase 2c — Hero copy: title «Understand the energy transition, together»; subtitle two players/trade-offs (no em dash); no CTA in Hero (Get in touch resta in navbar + Contact)",
    "Phase 2c — Game copy approvato così com'è: title cooperative game about energy; body net zero/shared decisions; TALK/PLAN/PLAY card bodies invariati",
    "Phase 2c — Energy + Learning Goals approvati così com'è: title future; body centre climate transition; 4 SDG card bodies invariati",
    "Phase 2c — Testimonials approvati così com'è: titoli target/experts; 3 quote studenti + 2 esperti invariati",
    "Phase 2c — Partners approvati così com'è: title energy sector; funded row Project funded by; linkLabel website →",
    "Phase 2c — Team copy approvato B2: interaction designers, soft spot education, hands-on games/visual tools/workshops, prototype fast; nomi ritratti capitalizzati; no istituzioni nel body",
    "Phase 2c — Contact body B1: teacher/school/partner/curious; demos, workshops, partnerships; titolo «Want to learn more?» e CTA «Get in touch» invariati; Footer tagline = SITE",
    "Phase 2c — Approvazione finale: copy + metadata + favicon K giallo; Hero senza CTA; committato e pushato su main",
  ],
  next: [
    "Opzionale — Cleanup: /contact-preview, blocchi legacy in sections.js (About, Features, HowItWorks, CTA)",
    "Opzionale — Domande visive: navbar, colori CTA",
    "Opzionale — Versione IT per stakeholder locali",
  ],
  blockers: [],
  fonts: {
    display: {
      family: "Chillax Bold",
      tailwind: "font-display (alias font-chillax)",
      path: "public/fonts/Chillax-Bold.otf",
    },
    body: {
      family: "Outfit",
      tailwind: "font-body (alias font-outfit)",
      source: "next/font/google (variable 100–900)",
    },
  },
  cta: {
    type: "radial-gradient",
    stops: ["#fad724 0%", "#e9b717 50%", "#d8970a 100%"],
    textColor: "#503b14",
    note: "Non usare flat #fad724 per CTA — solo per highlight sotto testo",
  },
  sdgColors: {
    scoped: true,
    rule: "Usare bg-sdg-* SOLO nelle card Learning Goals",
    values: {
      red: "#C5192D",
      yellow: "#FCC30B",
      brown: "#BF8B2E",
      green: "#3F7E44",
    },
  },
  gameCards: {
    scoped: true,
    rule: "Usare game-card-talk/plan/play SOLO in GameSection",
    midTones: { talk: "#e05773", plan: "#2b9295", play: "#da6a30" },
  },
  tagLabels: {
    scoped: true,
    rule: "tag-student / tag-psychologist globali (pill + team); tag-student-teal / tag-student-play / tag-expert-energy SOLO TestimonialsSection",
    text: {
      student: "#435117",
      studentTeal: "#005a5d",
      studentPlay: "#9c3b09",
      psychologist: "#732474",
      expertEnergy: "#9c1c36",
    },
    studentGradient: { start: "#8eaa2c", end: "#708721" },
  },
  definitive: [
    "brand name KeepItCool (display KEEP IT COOL nel footer)",
    "copy intent in project-brief.js",
    "palette cream/ink/yellow gradient CTA",
    "Chillax + Outfit",
    "SDG colors scoped to 4 cards",
    "section order from Figma (Testimonials tra Learning Goals e Partners)",
  ],
  indicative: ["spacing", "exact font sizes", "hero assets"],
};

export const SDG_COLOR_RULE =
  "Token sdg-red, sdg-yellow, sdg-brown, sdg-green: solo componenti SdgCard / LearningGoals.";
